---
- name: services | Ensuring drbd Service Is Enabled On Boot
  systemd:
    name: drbd
    enabled: true
    daemon_reload: true
    state: started
  become: true

- name: services | Ensuring heartbeat Service Is Enabled On Boot
  systemd:
    name: heartbeat
    enabled: true
    daemon_reload: true
    state: started
  become: true
  when: drbd_use_heartbeat
